name: CICD

on:
 workflow_dispatch:
 release:
   types: [created]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Publish Artifact
      run: sbt test
    - name: Publish package
      run: sbt publish
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGING }}


